### ISSUE TITLE
WKND default Translation Rules for referenced content

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd#121]
ootb translation rules reference resource types of Core Components for rules around referenced Content Fragments, Experience Fragments, and Images:

![image](https://user-images.githubusercontent.com/8974514/88100858-03d0e500-cb52-11ea-8d74-67bd8a99cc4b.png)

The resource types used by WKND will be different, i.e `wknd/components/image`. Additional translation rules should be installed automatically:

![image](https://user-images.githubusercontent.com/8974514/88101060-4eeaf800-cb52-11ea-9780-cdff860db769.png)

**Comment by knennigtri** [comment]
Hey @godanny86,
My coworker dove a bit deeper into this and we realized, it's not because WKND is missing those rules, rather the new XF/CF core components are missing those rules. The translation rules are picked up with sling:resourceSuperType of the proxy components too. He has tested this and confirmed. So, although this will fix translations for WKND, maybe this is an issue that should be brought up in the core components project or the AEM product itself?

**Comment by godanny86** [comment]
@knennigtri can I close this issue?

**Comment by knennigtri** [comment]
Yep.
