### ISSUE TITLE
Root container of WKDN templates/pages is not responsive

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-guides-wknd#130]
With #110, the responsive grid was replaced by WKND container (which proxies the Core Components container). However, the Core Components container is not responsive by default (one needs to set `layout="responsive"` property). This makes the rest of the containers and components behave erratically when using responsive layouting.

**Comment by godanny86** [comment]
@vladbailescu is there a specific rendering issue you notice? The `layout="responsiveGrid"` is used but only in situations where the a responsive layout is needed: https://github.com/adobe/aem-guides-wknd/search?q=layout%3D%22responsiveGrid%22&unscoped_q=layout%3D%22responsiveGrid%22. 

Since Core Components does not turn it on by default I thought it was best to only use it when needed...

The Page Template generated by the archetype should then also be updated? 

https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/structure/.content.xml#L12

**Comment by vladbailescu** [comment]
Yes, we saw some issues when trying to resize the container directly under the root.
