### ISSUE TITLE
`/conf/wknd` should be overwritten to `sling:Folder` resource type for instances using older versions of WKND

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-guides-wknd#174]
Due to https://github.com/adobe/aem-guides-wknd/blob/b8e73b2f5b1d406b7079a717a52cbcdff6ab3846/ui.content.sample/src/main/content/META-INF/vault/filter.xml#L14, `/conf/wknd` might have been created as `nt:folder` on instances where older versions of WKND were installed. If somebody wants to upgrade to a newer version they won't be able as it will not allow `nt:unstructured` nodes (like https://github.com/adobe/aem-guides-wknd/tree/master/ui.content/src/main/content/jcr_root/conf/wknd/_sling_configs).

Although `/conf/wknd` is defined as `sling:Folder` in https://github.com/adobe/aem-guides-wknd/blob/d4246244ddbb3b15c6397a50bfcd59ecba6277c2/ui.content/src/main/content/jcr_root/conf/wknd/.content.xml#L3, this does not overwrite old `nt:folder` due to `merge` filter in https://github.com/adobe/aem-guides-wknd/blob/ac011f5d622d254421a0c26db93af9008e4f2e65/ui.content/src/main/content/META-INF/vault/filter.xml#L3

**Comment by godanny86** [comment]
@vladbailescu is this still a valid issue?

**Comment by joerghoh** [comment]
it is still valid.

**Comment by godanny86** [comment]
The issue: https://github.com/adobe/aem-guides-wknd/issues/125 did cause the node `/conf/wknd` to be created as an `nt:folder`. This issue has been fixed and with new deployments `/conf/wknd` is correctly creating the node with a primary type of `sling:Folder`. 

For customers that have an environment in which the `nt:folder` exists the recommendation is to apply a one-time fix to correct the folder. This can be done manually by simply deleting the folder at `/conf/wknd` and re-deploying the latest version of WKND. 

Alternatively the following actions can be performed for higher level environments that can only be fixed with a code deployment:

1. Checkout the latest version of WKND and update the [ui.content/src/main/content/META-INF/vault/filter.xml](https://github.com/adobe/aem-guides-wknd/blob/master/ui.content/src/main/content/META-INF/vault/filter.xml#L3)

    ```diff
    - <filter root="/conf/wknd" mode="merge"/>
    + <filter root="/conf/wknd" />
    ```
 
    This will cause the `/conf/wknd` folder to be completely overwritten and correct the folder. An example of this one time fix can be found here: https://github.com/adobe/aem-guides-wknd/commit/06ef6e8c411f646fa4589e7696e62f13bfbb0f83

1. Deploy WKND with the updated `filter.xml` file using Cloud Manager and CI/CD pipeline
1. After this is done, revert the changed to the `filter.xml` file and continue to deploy the code base normally.

Performing the above steps is a one time activity, and is preferable to modifying the project. 

The error found in logs with the incorrect `nt:folder` primary type is:

```
javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /conf/wknd[[nt:folder]]: No matching definition found for child node sling:configs with effective type [nt:unstructured, rep:AccessControllable]"
```

**Comment by kwin** [comment]
You can easily enforce a certain primary type without overwriting everything below with the following pattern

```
<filter root="/conf/wknd" >
   <!--only overwrite the node /conf/wknd and all its properties, but no sub nodes -->
   <include pattern="/conf/wknd">
</filter>
```
