### ISSUE TITLE
com.day.cq.search,version=[1.4,2) -- Cannot be resolved

### ISSUE THREAD

**Issue by shajiahmed** [adobe/aem-guides-wknd#211]
I have latest version of aem-guides-wknd 0.2.1 on AEM 6.5.8.0  using core component 2.15.2
### Expected Behaviour
All bundles should be active

### Actual Behaviour
com.day.cq.search,version=[1.4,2) -- Cannot be resolved

#### Logs taken while reproducing problem
Unable to resolve aem-guides-wknd.core [582](R 582.2): missing requirement [aem-guides-wknd.core [582](R 582.2)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0))) Unresolved requirements: [[aem-guides-wknd.core [582](R 582.2)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0)))])

**Comment by godanny86** [comment]
hi @shajiahmed did you use the classic profile? https://github.com/adobe/aem-guides-wknd#building-for-aem-6xx

**Comment by clstia** [comment]
@godanny86 what should I do if the classic profile is said to be missing?

**Comment by davidjgonzalez** [comment]
@clstia This very much looks like you are installing the AEM as a Cloud Service OSGi bundle for WKND core on AEM 6.5.

Whenever you are building the WKND project for AEM 6.x, make sure to use the `classic` Maven profile, which will instruct the WKND Core project to build using the AEM 6.5 UberJar rather than the AEM SDK API Jar -- which have different versions of some dependencies.

You can do this form the command line, by adding the `-Pclassic` argument, and most IDE's that have Maven runners have a way to default specific Maven profiles to always run (but you'll have to check your IDE for how to do that)

```
$ mvn clean install -PautoInstallSinglePackage -Pclassic
``

In care you're curious - here's the definition of the classic profile (so it definitely is there)
https://github.com/adobe/aem-guides-wknd/blob/master/core/pom.xml#L154-L322
