### ISSUE TITLE
Compatible version to use for Java8 and Maven 3.3.9 on AEM6.5.9.0

### ISSUE THREAD

**Issue by kdesineedi** [adobe/aem-guides-wknd#332]
I am getting build errors while building the wknd project while on Java 8 and Maven 3.3.9.I am on AEM 6.5.9.0
Could you please suggest the appropriate version to use for WKND tutorial for this config as I cannot upgrade any of my versions as my project is on that stack.

**Comment by godanny86** [comment]
Hi @kdesineedi is this for following the tutorial or just installing the site?

I think you will need to downgrade Core Components below 2.18.0, like https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.17.14. 

So if following the tutorial, using https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-35 should work. Release https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-1.1.0 should also work I think...

**Comment by kdesineedi** [comment]
Upgraded mvn version to Apache Maven 3.6.0 to resolve. Should the required version of mvn be upgraded to this version for the new archetype ?
Also the build succeeded with the following warning:
`The requested profile "classic" could not be activated because it does not exist. `  when executed with 
`mvn clean install -PautoInstallSinglePackage -Pclassic`

**Comment by godanny86** [comment]
Hi @kdesineedi, glad you got it working!

1. I would file an issue in the AEM Project Archetype for the minimum Maven requirement: https://github.com/adobe/aem-project-archetype
2. The `classic` profile is just something added to the wknd project so that we can have a single code base that is backwards compatible with 6.5 builds. If you generated your project using the Archetype it will not be included.

**Comment by kdesineedi** [comment]
Thanks @godanny86
