### ISSUE TITLE
WKND Image List Component does not reflect unpublish state

### ISSUE THREAD

**Issue by hchung416** [adobe/aem-guides-wknd#55]
When using the new Image List component with the option to Build List Using: Child Pages, the resulting list of pages includes unpublished pages. I would expect that unpublished pages would not be included in the list.

**Comment by godanny86** [comment]
@hchung416 this behavior (seeing unpublished pages) occurs on the author instance only, yes?

I think this a nuance of AEM author + publish model. In order to keep the logic of the Core Component List simple it just grabs child pages that exist on the current instance (regardless of author v. publish, published v. unpublished)

**Comment by hchung416** [comment]
Ah.. interesting. May be confusing for the uninitiated, but I get the reasoning. Thanks for clarification @godanny86.
