### ISSUE TITLE
WKND uses unresolvable request paths for images

### ISSUE THREAD

**Issue by mkolmhuber** [adobe/aem-guides-wknd#94]
The ResourceResolver cannot resolve the request path below (as well as many other similar request paths on the WKND site). Either implement a custom ResourceResolver for the WKND application or implement your resources differently. IMHO it is a Sling paradigm that a request path can be resolved to a resource, in particular if it is a resource.

/content/wknd/us/en/adventures/ski-touring-mont-blanc/jcr%3acontent/root/responsivegrid/carousel/item_1571168419252.coreimg.jpeg/1572285729016.jpeg

**Comment by mkolmhuber** [comment]
Changing "/jcr%3acontent/" to "/_jcr_content/" already helps.

**Comment by godanny86** [comment]
@mkolmhuber what version of AEM are you using? Also author/publish?

If you are not aware, WKND primarily uses https://github.com/adobe/aem-core-wcm-components and I believe the path you listed is one created by Image component by AEM core Components: https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image

**Comment by davidjgonzalez** [comment]
@mkolmhuber How/where did you get the above URL?  

The problem you're having is what you've pasted in above, is an encoded URL (note the `%3a` instead of a `:` in `jcr:content`). Sling's ResourceResolver doesnt automatically decode paths, since it expects JCR paths rather than encoded URLs. If you want to pass that URL into a `resourceResolver.resolve(..)` you'd need to ensure the URL is decoded first.

`_jcr_content` is a special "munging" that Sling does/understands for path segments when it converts them to paths (IIRC, via the HTML Transform factory? perhaps part of `resourceResolver.map(..)`) that has `:` in them.  Typically AEM will automatically write instances of `jcr:content` to `_jcr_content` when output paths in HTML (at least to "linking" attributes like `src` or `href`)

This is a roundabout way of saying, if you have URLs you want to resolve to paths using direct calls to `resourceResolver.resolve(..)` or `resourceResolver.getResource(..)`, Sling expect you to ensure they have been decoded into paths that Sling can understand. If you are sending HTTP Requests using encoded URLs (ie. your browser makes a HTTP GET to the URL you pasted) then Sling's Request processing framework will decode it automatically.

**Comment by godanny86** [comment]
@mkolmhuber closing this for now. Feel free to re-open if you have more info.
